import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import Extra from "@/components/Extra";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <meta charSet="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Facial Age Estimaion - Insomniac </title>
    </head>
    <body className={inter.className}>
      <Nav />
      <main>
      {children}
      <Extra />
      </main>
        
      <hr />
      <Footer />
    </body>
    </html>
  );
}
