# Generated by Django 4.1.13 on 2024-08-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeEst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img_upload/')),
                ('result', models.CharField(blank=True, max_length=405, null=True)),
                ('desc', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
